version: "3"

services:
  server:
    build: ./
   restart: always
   ports:
    - "8080:8080"
  environment:
 - POSTGRES_ADDR=postgres
 - POSTGRES_HOST: "localhost"
 - POSTGRES_PORTS:
     - "5432:5432"
 - POSTGRES_DB: "postgres"
 - POSTGRES_PASSWORD: "postgres"
 - POSTGRES_USER: "postgres"

  postgres:
  image: "postgres:14.2-alpine"
  restart: "always"
