server:
  host: 0.0.0.0
  port:
    http: 8080
  timeout:
    server_timeout: 30
db:
    driver: postgres
    user: postgres
    password: postgres
    hostdb: postgres
    portdb: 5432
    dbname: postgres
    mode: disable
